### ISSUE TITLE
微信分享好友及朋友圈出错-选人无法发送

### ISSUE THREAD

**Issue by FTD-ZF** [hss01248/UmengUtil#1]
在点击微信分享后弹出选择朋友的界面，然胡选完人之后无法发送，点击发送没效果；
点击分享朋友圈直接崩溃 。

**Comment by hss01248** [comment]
log?

**Comment by FTD-ZF** [comment]
微信回调中的errCode是-6，然网上查了微信是签名不对，然后改了再次调用微信分享还是可以进入到微信的界面选人之后无法发送；然后点击朋友圈就是直接崩溃。(qq的可以用微博还没尝试)

**Comment by hss01248** [comment]
你不要用我的demo里的,里面的签名文件我已经删了.你要自己配
